pipeline:
  name: grant-microservice
  identifier: grantmicroservice
  projectIdentifier: IDA
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubOrgLevelConnector
        repoName: libraryManagement
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: api
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: devops-central
                  identifier: devopscentral
                  spec:
                    connectorRef: account.Github
                    repoName: gtbanfield/devops-central
                    build:
                      type: branch
                      spec:
                        branch: main
                  description: devops-central
              - step:
                  type: Run
                  name: Prepare-Bootstrap
                  identifier: PrepareBootstrap
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine:latest
                    shell: Sh
                    command: |-
                      pwd
                      ls -la
                      sleep 10
                      cd gtbanfield/devops-central
                      cp python.py ../../
                      cp Dockerfile ../../
                      cd ../../
                      ls -la            
              - step:
                  type: Run
                  name: Mvn
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.9-amazoncorretto-17-al2023
                    shell: Sh
                    command: |-
                      java --version
                      mvn clean install -DskipTests
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: gtbanf1979/maven:v1
                    tags:
                      - mslatest
